twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        contact_email: 'o.girgiel@gmail.com'
        web_site: 'www.oggies.go.jy.fr'
        compte_instagram: Instagram
        compte_pinterest: autre
        copyright: 'Copyright © 2021 - Odile Girgiel'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
